version: "3"

services:
  data:
    container_name: database
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/init_data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    env_file:
      - .env


  backend:
    container_name: nest
    build:
      context: services/backend
      dockerfile: Dockerfile
    restart: always
    command: yarn start:dev
    volumes:
      - ./services/backend:/home/backend
      - /home/backend/node_modules
    ports:
      - "3333:3333"
    env_file:
      - .env

volumes:
  postgres: